### ISSUE TITLE
Drop Name?

### ISSUE THREAD

**Issue by mwc360** [colindembovsky/cols-agent-tasks#135]
How do i identify what the Drop Name is for a DACPAC Schema Compare? I've tried the Build Pipeline name, alias, just drop, etc. I've tried a lot of things and I get the error 
##[warning]There is no drop with the name X.

Thanks

**Comment by colindembovsky** [comment]
Hi @mwc360 

I have these 2 steps in my pipeline if that helps:
```
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: DacPacReport@1
  displayName: 'DacPac Schema Compare FabFiber.Schema.dacpac'
  inputs:
    dacpacName: FabrikamFiber.Schema
    targetDacPacPath: '$(Build.ArtifactStagingDirectory)'
```

For "classic" builds, I have:
- "drop" specified as the name of the artifact on a Publish Build Artifact task, followed by
- Dacpac Report Task using "drop" as the name of the drop

Are you using classic or yml? If yml, can you post a snippet of your yml build?
