### ISSUE TITLE
Error When Perform Dacpac Schema Compare in YAML version of Azure Build pipeline 

### ISSUE THREAD

**Issue by wildanmuhlis2** [colindembovsky/cols-agent-tasks#174]
Hi,

I use YAML version of the azure build pipeline.

There is no option for checking OAuth there.

Is this error caused by it?

```
Starting: DacPacReport
==============================================================================
Task         : DacPac Schema Compare
Description  : Provides a report on database model changes since the last build
Version      : 1.2.114
Author       : Colin Dembovsky (colinsalmcorner.com)
Help         : [More Information](https://github.com/colindembovsky/cols-agent-tasks/tree/master/Tasks/DacPacReport)
==============================================================================
"C:\ProgramData\Chocolatey\bin\vswhere.exe" -version [15.0,16.0) -latest -format json
"C:\ProgramData\Chocolatey\bin\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
Attempting to get System.AccessToken
Successfully obtained System.AccessToken
##[error]Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
Finishing: DacPacReport
```

This is my task definition
```

- task: DacPacReport@1
  inputs:
    dropName: 'drop'
    dacpacName: 'Demo.Database'
    targetDacPacPath: '$(Agent.BuildDirectory)\s\Pipeline-Demo.Database\bin\Debug\'
```
